server:
  port: 1314
#  ssl:
#    enabled: true
#    key-store: classpath:ssl/zwgl.org.cn.jks
#    key-store-password: go7199u4
#    key-store-type: JKS
spring:
  datasource:
    url: jdbc:mysql://.122.123.251:3306/yuntong?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: yuntong
    password: dnfXb2TeHyaazsr
    driver-class-name: com.mysql.cj.jdbc.Driver
    # application.yml
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

mybatis-plus:
  global-config:
    db-config:
      # id生成策略 auto为数据库自增
      id-type: auto

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 604800
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  #读请求头
  is-read-header: true
  is-read-cookie: false
  is-read-body: false


logging:  #日志级别设置
  level:
    top.javatool.canal.client.client.AbstractCanalClient: WARN  # 屏蔽 INFO 日志



